#' termr: a modern reactive terminal UI framework for R
#'
#' termr builds interactive terminal applications from a tree of widgets.
#' The pipeline is:
#'
#' widget tree -> reactive state -> events -> layout -> virtual screen ->
#' screen diff -> ANSI patch -> terminal.
#'
#' Start with [app()], the widget constructors ([vertical()], [horizontal()],
#' [label()], [button()], [input()]) and [run()]. Custom widgets are
#' created with [widget()] and [reactive()]. Applications are tested
#' headlessly with [test_app()].
#'
#' @keywords internal
#' @importFrom R6 R6Class
#' @importFrom processx process
"_PACKAGE"

# Methods generated by widget() refer to R6's `self` and `super`, which R6
# provides when the class is instantiated.
utils::globalVariables(c("self", "super", "private"))
